INSERT INTO TBL_AGENDA (NOME, COMPROMISSO, DIA, HORARIO, LOCALIZACAO)
 VALUES ('ADRIANO', 'TAREFA1', '01/01', '11:30', 'ARARUNA');
 INSERT INTO TBL_AGENDA (NOME, COMPROMISSO, DIA, HORARIO, LOCALIZACAO)
 VALUES ('BRENO', 'TAREFA2', '02/01', '12:30', 'BAR');
 INSERT INTO TBL_AGENDA (NOME, COMPROMISSO, DIA, HORARIO, LOCALIZACAO)
 VALUES ('CALEBE', 'TAREFA3', '03/01', '13:30', 'COMBATE');